version: "3.7"
services:
  yuejuan_streamlit:
    build: ./
    container_name: yuejuan_streamlit
    ports:
      - "8888:8888"
    working_dir: "/workspaces/yuejuan_streamlit"
    volumes:
      - /Volumes/myDriver/github/python3/yuejuan_streamlit:/workspaces/yuejuan_streamlit
    command: "streamlit run auth.py --server.port 8888"

  liusu_streamlit:
    build: ./
    container_name: liusu_streamlit
    ports:
      - "8899:8899"
    working_dir: "/workspaces/liusu"
    volumes:
      - /Volumes/myDriver/github/python3/liusu:/workspaces/liusu
    command: "streamlit run auth.py --server.port 8899"