version: "3.7"
services:
  streamlit:
    build: ./
    container_name: liusu_streamlit
    ports:
      - "8888:8888"
    working_dir: "/workspaces/liusu"
    volumes:
      - /Volumes/myData/github/liusu:/workspaces/liusu
    command: "streamlit run index.py --server.port 8888"